<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InformasiBarangPendingSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'pending_id'          => 1,
                'pending_kode'        => 'p-sar404pa1',
                'pending_nama'        => 'Papan Tulis',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-01 02:04:33',
                'updated_at'          => '2022-03-01 02:04:33'
            ],
            [
                'pending_id'          => 2,
                'pending_kode'        => 'p-sar404pa2',
                'pending_nama'        => 'Papan Tulis',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-01 02:04:33',
                'updated_at'          => '2022-03-01 02:04:33'
            ],
            [
                'pending_id'          => 3,
                'pending_kode'        => 'p-sar404le3',
                'pending_nama'        => 'Lemari',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-01 02:05:14',
                'updated_at'          => '2022-03-01 02:05:14'
            ],
            [
                'pending_id'          => 4,
                'pending_kode'        => 'p-kom404cp4',
                'pending_nama'        => 'CPU',
                'kategori_fk'         => 'Komputer',
                'pending_merk'        => 'HP',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 1,
                'created_at'          => '2022-03-01 02:06:18',
                'updated_at'          => '2022-03-01 02:06:18'
            ],
            [
                'pending_id'          => 5,
                'pending_kode'        => 'p-kom404mp5',
                'pending_nama'        => 'Mpuse',
                'kategori_fk'         => 'Komputer',
                'pending_merk'        => 'Logitech',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 1,
                'created_at'          => '2022-03-01 02:07:25',
                'updated_at'          => '2022-03-01 02:07:25'
            ],
            [
                'pending_id'          => 6,
                'pending_kode'        => 'p-kom404mo6',
                'pending_nama'        => 'Monitor',
                'kategori_fk'         => 'Komputer',
                'pending_merk'        => 'HP',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 1,
                'created_at'          => '2022-03-01 02:08:23',
                'updated_at'          => '2022-03-01 02:08:23'
            ],
            [
                'pending_id'          => 7,
                'pending_kode'        => 'p-kom404ke7',
                'pending_nama'        => 'Keyboard',
                'kategori_fk'         => 'Komputer',
                'pending_merk'        => 'Logitech',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 1,
                'created_at'          => '2022-03-01 02:09:05',
                'updated_at'          => '2022-03-01 02:09:05'
            ],
            [
                'pending_id'          => 8,
                'pending_kode'        => 'p-sar409ku8',
                'pending_nama'        => 'Kursi',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.09',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-01 02:10:37',
                'updated_at'          => '2022-03-01 02:10:37'
            ],
            [
                'pending_id'          => 9,
                'pending_kode'        => 'p-sar409me9',
                'pending_nama'        => 'Meja Besar',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.09',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-01 02:11:10',
                'updated_at'          => '2022-03-01 02:11:10'
            ],
            [
                'pending_id'          => 10,
                'pending_kode'        => 'p-sar404me10',
                'pending_nama'        => 'Meja',
                'kategori_fk'         => 'Sarana',
                'pending_merk'        => '',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 2019,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 0,
                'created_at'          => '2022-03-02 00:50:56',
                'updated_at'          => '2022-03-02 00:50:56'
            ],
            [
                'pending_id'          => 11,
                'pending_kode'        => 'p-kom404mo11',
                'pending_nama'        => 'Mouse',
                'kategori_fk'         => 'Komputer',
                'pending_merk'        => 'Logitech',
                'pending_deskripsi'   => '',
                'pending_tahun_perolehan' => 0000,
                'pending_keadaan'     => 'BAIK',
                'pending_harga'       => 0,
                'lokasi_fk'           => 'R.4.04',
                'pending_keterangan'  => '',
                'pending_status'      => 1,
                'pending_dipinjamkan' => 1,
                'created_at'          => '2022-03-02 00:51:43',
                'updated_at'          => '2022-03-02 00:51:43'
            ],
        ];

        $this->db->table('informasi_barang_pending')->insertBatch($data);
    }
}
