<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PengelolaanBarangSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'pengelolaan_kode'     => 'tam-p-sar404pa1',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar404pa1',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:04:33',
                'updated_at'           => '2022-03-01 02:11:30',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-sar404pa2',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar404pa2',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:04:33',
                'updated_at'           => '2022-03-01 02:11:35',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-sar404le3',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar404le3',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:05:14',
                'updated_at'           => '2022-03-01 02:11:40',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-kom404cp4',
                'barang_fk'            => null,
                'pending_fk'           => 'p-kom404cp4',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:06:18',
                'updated_at'           => '2022-03-01 02:11:46',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-kom404mp5',
                'barang_fk'            => null,
                'pending_fk'           => 'p-kom404mp5',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:07:25',
                'updated_at'           => '2022-03-01 02:11:51',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-kom404mo6',
                'barang_fk'            => null,
                'pending_fk'           => 'p-kom404mo6',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:08:23',
                'updated_at'           => '2022-03-01 02:12:37',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-kom404ke7',
                'barang_fk'            => null,
                'pending_fk'           => 'p-kom404ke7',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:09:05',
                'updated_at'           => '2022-03-01 02:12:09',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-sar409ku8',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar409ku8',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:10:37',
                'updated_at'           => '2022-03-01 02:12:13',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-sar409me9',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar409me9',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-01',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-01 02:11:10',
                'updated_at'           => '2022-03-01 02:12:19',
            ],
            [
                'pengelolaan_kode'     => 'tam-p-sar404me10',
                'barang_fk'            => null,
                'pending_fk'           => 'p-sar404me10',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-02',
                'jenis_fk'             => 'TAMBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-02 00:50:56',
                'updated_at'           => '2022-03-02 00:55:03',
            ],
            [
                'pengelolaan_kode'     => 'uba-p-kom404mo11',
                'barang_fk'            => 'kom404mo5',
                'pending_fk'           => 'p-kom404mo11',
                'user_fk'              => 'admin',
                'pengelolaan_tanggal'  => '2022-03-02',
                'jenis_fk'             => 'UBAH',
                'pengelolaan_status'   => 1,
                'pengelolaan_keterangan'=> null,
                'created_at'           => '2022-03-02 00:51:43',
                'updated_at'           => '2022-03-02 00:57:59',
            ],
        ];

        $this->db->table('pengelolaan_barang')->insertBatch($data);
    }
}
